model_provider = "openai"
allow_amend = false

[openai]
api_base = "https://api.openai.com/v1"
model = "gpt-5.5"
retries = 2
proxy = ""

[output]
conventional_commit = true
conventional_commit_prefix_format = "{{ prefix }}: "
lang = "en"
show_per_file_summary = false
